# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Effacy Theme"
license = "MIT"
licenselink = "//github.com/alexout/hugo-theme-effacy/blob/master/LICENSE.md"
description = ""
homepage = "//github.com/alexout/hugo-theme-effacy/"
tags = ["portfolio", "company", "contact form", "timeline", "google analytics"]
features = ["", ""]
min_version = 0.17

[author]
  name = "Alex Blinov"
  homepage = "//github.com/alexout/"

# If porting an existing theme
[original]
  name = "Effacy"
  homepage = "//github.com/themebite/themebite.github.io/tree/master/demo/effacy"
  repo = "//github.com/themebite/themebite.github.io"
